### ISSUE TITLE
MTablePDF class namespacing

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#10]
The `MTablePDF` class should either have valid component prefix, i.e. `mod_checkmark_mtablepdf` or be namespaced. See https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions for details.

If you were using [Moodle class autoloading](https://docs.moodle.org/dev/Automatic_class_loading) this would force you to avoid this mistake.

**Comment by kaspot** [comment]
thanks - added to our todo list

**Comment by kaspot** [comment]
Should be fixed in the newest Moodle 2.8 version.
