### ISSUE TITLE
manual_cron.php requires non-existing file checkmark_pdf.php

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#11]
Actually, it seems the module is using task API now and the function `checkmark_cron()` has been removed so the whole script `manual_cron.php` is probably just a relict to be deleted.

**Comment by kaspot** [comment]
thanks - we'll check it

**Comment by kaspot** [comment]
Should be fixed in the newest Moodle 2.8 version.
