### ISSUE TITLE
If individual naming is enabled, "example" should not be forced

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#14]
The teacher might want to use the module in new scenarios (some Moodle teachers are very creative). Even if individual/custom naming feature is enabled, the module still prepends "example" to the custom name. I believe this should not happen - the module should display the custom name solely.

Alternatively, instead of hardcoded "example", there could be another setting field (defaulting to current "example") with the configurable text to prepend to all the items (and empty value would be valid).

**Comment by kaspot** [comment]
thanks for this comment - would be a good feature

**Comment by kaspot** [comment]
We will implement this feature for the next 2.9 version of our plugin. Again - thanks for the great idea.

**Comment by kaspot** [comment]
Just a short notice - we've implemented this issue for 2.9 version of Moodle and we will release it at the end of February/beginning of March.
