### ISSUE TITLE
Coding error in English string syntaxis prevents translation of some Moodle branches in AMOS.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_checkmark#16]
Hi,
 I recently  translated into Mexican Spanish your checkmark module plugin in AMOS (https://lang.moodle.org/ ), but I noticed that AMOS only houses translations for the Moodle 2.8 branch , even though you have 2.6, 2.7 and 2.8 Moodle branches listed for your plugin.

Please see Moodle developer's documentation at  https://docs.moodle.org/dev/Translating_plugins#If_translations_are_available_in_AMOS_for_some_Moodle_branches_but_not_available_for_other_branches

All similar cases seen with Moodle plugins in the near past have been caused by coding errors (as described)  and have beeen relatively easy to fix.

I will be looking forward to seeing soon an updated version of your plugin.

**Comment by mkemmerling** [comment]
Hi,

you are right, we didn't use AMOS in the past (the 2.6 and 2.7 versions directly include the german lang files).

I am not sure if I understand you right, but currently it isn't possible to translate the plugin due to ticket #13. We hope to get this fixed soon, one way or another.

Regards,
Markus Kemmerling

**Comment by germanvaleroelizondo** [comment]
Hi,
You are right.

I  think that the best solution (plan A) would be to fix whatever seems to be causing the problem (perhaps probably caused by the presence of escaped single quote characters), and AMOS would then import the English language strings files cleanly. But I am not a programmer, I am a veterinarian.

Plan B would be to ask David Mudrák (plugin database master) to manually import these files into AMOS (as he offered).

AMOS is extremely important for all language packs. Including a translation (or several translations) inside the plugin ZIP file is less desirable, as there would be no easy way for other translators (like me)  to properly translate your plugin into the many (100+) languages that Moodle supports.

**Comment by mkemmerling** [comment]
We already forwarded the problem to our developer to see if he can fix the problem in the lang file (plan A). If not, we will certainly fall back to plan B.

**Comment by germanvaleroelizondo** [comment]
Thanks.

**Comment by kaspot** [comment]
Should be fixed.

**Comment by germanvaleroelizondo** [comment]
Thanks for fixing this.
