### ISSUE TITLE
wrong results exported

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#17]
we have this issue with this plugin on our productive site:
- right after submitting, a student will see what he submitted, but the order of the examples will be mixed up
- for the teacher, he will see the correct submissions in the submission overview
- as soon as the teacher switches to "export", wrong results are shown, and any file type that is exported will show these wrong results
  (see attached screenshots)

interestingly, we only have this issue on our productive site, i could not replicate it on our test site, even though both have the exact same version of the plugin installed.

productive site:
Moodle 2.8.7 (Build: 20150706)
postgres (9.4.4)

test site:
Moodle 2.8.7 (Build: 20150706)
postgres (9.3.8)

![ss2](https://cloud.githubusercontent.com/assets/13886080/10821573/63f22576-7e53-11e5-893b-dd82d0634bde.png)
![ss3](https://cloud.githubusercontent.com/assets/13886080/10821574/63f24646-7e53-11e5-9708-53804bf398e9.png)
![ss1](https://cloud.githubusercontent.com/assets/13886080/10821575/63f5386a-7e53-11e5-9113-a1bb4bd4f182.png)

**Comment by kaspot** [comment]
Thanks for reporting this bug - we will forward it to our developer.
Could you please give me the version of the module you are using.

**Comment by kaspot** [comment]
Can I ask you to send me the settings page of the checkmark instance - the best would be a screenshot of the settings page of this checkmark instance.

**Comment by stemiwe** [comment]
i had this issue with a version i downloaded half a year ago, and now replaced it with the latest available version (2015071504). screenshot of settings is attached. 

settings are all on default and identical on the productive site, which has the issue, and the test site, where it works as expected
![ss4](https://cloud.githubusercontent.com/assets/13886080/10941115/3aec745e-830a-11e5-906f-ef29229629dc.png)

**Comment by kaspot** [comment]
Hi, thanks for the additional screenshot. Is it really the settings page of the checkmark from your first message. Because in the first screenshot it seems that you are not using individual naming and in the settings page it seems like you do. You can also see this when you compare the Checkmark names. Could you please send me the settings page and the result page (with wrong layout/order) of one and the same checkmark instance.

**Comment by stemiwe** [comment]
yes, it is

the screenshot from the result page is already in my first post

both are from the same instance

**Comment by kaspot** [comment]
would it be possible to export this checkmark and send me the file - maybe via email - katarzyna.potocka@tuwien.ac.at

**Comment by stemiwe** [comment]
im just trying to reproduce the issue and it seems it is gone right now. at least in my test course the results show up as normal, with the exact same activity/URL.

im contacting the lector who reported the problem in the first place. seems really weird that it just vanished, since we did not change anything on the site. do you think it could be a language issue? we are using both german and english.

**Comment by kaspot** [comment]
honestly I have no clue what could cause this problem - but we couldn't reproduce it on any of our testing instances.
