### ISSUE TITLE
results are not displayed if activity is set into group mode

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#18]
Using moodle v3.3.1 20170714
and mod_checkmark v3.3.2 2017081002

when trying to view the attempts on a checkmark activity, where group mode is activated, all I get is "error reading from database" - more detailed debug info can be found below. This happens on two separate Moodle instances - our productive and our test environment.

I have to say that we are very disappointed by this plugin overall - it already caused us trouble late in 2015 when it mixed up results in a seemingly random way (I posted the issue back then, but we couldnt reproduce it). We already wanted to uninstall it, but gave the new version another chance.

Now we have this rather big issue, along with another weird issue that I will post after this. This plugin seems to be very poorly written to be honest, and does not meet the expectations I normally have from AMC plugins.

----------------------------------

Detailed debug info:

Error reading from database

More information about this error

×Debug info: ERROR: column "grpq.groups" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4: ...ified AS timesubmitted, f.timemodified AS timemarked, groups
^
SELECT
u.id, ' ' AS selection, ' ' AS picture, u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email , u.email,
s.id AS submissionid, f.id AS feedbackid, f.grade, f.feedback,
s.timemodified AS timesubmitted, f.timemodified AS timemarked, groups
FROM mdl_user u LEFT JOIN mdl_checkmark_submissions s ON u.id = s.userid AND s.checkmarkid = $1
LEFT JOIN mdl_checkmark_feedbacks f ON u.id = f.userid AND f.checkmarkid = $2 LEFT JOIN (SELECT MAX(grps.courseid), MIN(grps.name) AS groups, grpm.userid AS userid
FROM mdl_groups_members grpm
LEFT JOIN mdl_groups grps ON grps.id = grpm.groupid
WHERE grps.courseid = $3
GROUP BY grpm.userid
ORDER BY MIN(grps.name) ASC) AS grpq ON u.id = grpq.userid 
WHERE u.id IN ($4,$5,$6)
GROUP BY u.id, s.id, f.id, u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email , u.email
ORDER BY lastname ASC LIMIT 10
[array (
0 => '81',
1 => '81',
2 => '2516',
3 => 5,
4 => 4,
5 => 3,
)]
Error code: dmlreadexception
×Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 776 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 171 of /mod/checkmark/classes/submissionstable.php: call to pgsql_native_moodle_database->get_records_sql()
line 1630 of /lib/tablelib.php: call to mod_checkmark\submissionstable->query_db()
line 2402 of /mod/checkmark/locallib.php: call to table_sql->out()
line 2302 of /mod/checkmark/locallib.php: call to checkmark->submissions_tab()
line 1403 of /mod/checkmark/locallib.php: call to checkmark->display_submissions()
line 62 of /mod/checkmark/submissions.php: call to checkmark->submissions()

**Comment by kaspot** [comment]
Thank you for reporting this bug. We will include specific Behat tests so that this bug shouldn't happen again. And concerning the bug fixing — our developer is already on it.

**Comment by mkemmerling** [comment]
Fixed in v3.3.3.
