### ISSUE TITLE
duplicating a mod_checkmark activity results in database error

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#20]
Using moodle v3.3.1 20170714
and mod_checkmark v3.3.2 2017081002

if I try to duplicate a checkmark activity, even a fresh and empty one, I get an error message:

Coding error detected, it must be fixed by a programmer: Invalid database query parameter value

File: /lib/dml/moodle_database.php
Line: 846

Objects are are not allowed: stdClass
Error code: codingerror
* line 846 of /lib/dml/moodle_database.php: coding_exception thrown
* line 865 of /lib/dml/moodle_database.php: call to moodle_database->detect_objects()
* line 773 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->fix_sql_params()
* line 1387 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
* line 1338 of /lib/dml/moodle_database.php: call to moodle_database->get_records_select()
* line 915 of /mod/checkmark/lib.php: call to moodle_database->get_records()
* line 1453 of /course/lib.php: call to checkmark_refresh_events()
* line 1406 of /course/lib.php: call to course_module_calendar_event_update_process()
* line 3492 of /course/lib.php: call to course_module_update_calendar_events()
* line 3361 of /course/externallib.php: call to duplicate_module()
* line 228 of /lib/externallib.php: call to core_course_external::edit_module()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

If I refresh the Moodle course afterwards, the activity seems to have been duplicated nevertheless.

**Comment by goggo24** [comment]
Thanks for reporting the issue. We also noticed it and it's alread fixed in checkmark **v3.3.3**
