### ISSUE TITLE
A space

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_checkmark#24]
**In this page: .../moodle/mod/checkmark/view.php?id=600**
![imagem](https://user-images.githubusercontent.com/14828021/35865787-5df6b6a8-0b4d-11e8-96c7-2e8dca5072b8.png)
![imagem](https://user-images.githubusercontent.com/14828021/35865933-bd9bb78e-0b4d-11e8-85af-edbcc2b2ffbc.png)

**Comment by phager-at** [comment]
Hi, I can't give you a quick fix right now, but I can give you a workaround.
In theme_boost you have the opportunity to set custom SCSS, so you could add the following styles:

```
#page-mod-checkmark-view #dates td.title {
    padding-right: 0.5em;
}
```
