### ISSUE TITLE
Is this OK?

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_checkmark#25]
![imagem](https://user-images.githubusercontent.com/14828021/36309135-5286d430-131b-11e8-9c90-02e4eca8a64b.png)

**Comment by goggo24** [comment]
Thanks for reporting. It doesn't effect the functionality of the plugin. We will fix it with the next version.

**Comment by dinism** [comment]
THANKS

**Comment by mkemmerling** [comment]
The missing lang string has been added in version 3.4.1 of the plugin. Thanks again for reporting.
