### ISSUE TITLE
mod_checkmark submissions cannot be reset via moodle course reset

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#26]
on moodle 3.4 with mod_checkmark v2018012700

mod_checkmark does not work with the moodle reset course feature

if I try to reset a course (from the course settings dropdown menu), and select either " Delete all submissions" or "Delete all date overrides" for "Checkmarks", I get this error message:

Exception - Call to undefined method pgsql_native_moodle_database::get_fieldset()

On our other Server (moodle 3.3 with mod_checkmark v2017081003), I get no error message, but the reset function fails anyways

**Comment by phager-at** [comment]
Hi,

thanks for reporting this bug. I'll have a look at it ASAP!

cheers,
Philipp

**Comment by phager-at** [comment]
Hi,

the bugfix is developed and currently under testing.

cheers,
Philipp

**Comment by stemiwe** [comment]
wow that was super quick :)

**Comment by mkemmerling** [comment]
The bug fix is now released here and at moodle.org (version 3.4.1).
Thanks again for reporting.
