### ISSUE TITLE
duplicating a checkmark activity does not correctly duplicate its settings

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#28]
using moodle 3.4.3 and checkmark plugin 3.4.1

**Bug description**

duplicating a checkmark activity does not correctly duplicate its setting, leading to orphaned attendance items in the gradebook

**Replicate**

1. Create a checkmark activity with these settings:

- Track attendance: YES
- Link attendance: YES
- Record attendance: YES

2. Duplicate the activity

3. Go to the settings of the duplicated activity, the settings will be:

- Track attendance: YES
- Link attendance: YES
- Record attendance: **NO**

4. Rename the duplicated activity and go to course grade setup

The attendance item for the duplicated activity is still in the gradebook, even though "Record attendance" seems to be set to "NO", it also is not renamed correctly if the parent activity is renamed.

5. Go to settings of the duplicated activity and change "Link attendance" to NO

The attendance item for the duplicated activity is removed from the gradebook

**Comment by phager-at** [comment]
Hi,

thanks for reporting. I'll take a look at it ASAP!

**Comment by phager-at** [comment]
Hi,

sorry for the delays. This issue will be fixed from v3.6.0 on - being released hopefully in January 2016!
(leaving this issue open, till the fixed version is published)

Thanks again for reporting and have a merry christmas!

cheers,
Philippp

**Comment by goggo24** [comment]
included in v.3.6.0 - coming soon!
