### ISSUE TITLE
Legacy naming format in settings.php

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#3]
See https://docs.moodle.org/dev/Plugin_contribution_checklist#Settings-storage

The settings like `checkmark_stdexamplecount` should be actually called `checkmark/stdexamplecount`. You will also probably need an upgrade step that would convert all existing settings from the main config table to the config_plugins one. A set of `get_config()` and `set_config()` calls in db/upgrade.php should do it well.

**Comment by kaspot** [comment]
is on our todo list and will be fixed asap.

**Comment by kaspot** [comment]
Should be fixed in the newest Moodle 2.8 version.
