### ISSUE TITLE
"check broken gradebook grades" does not seem to work, and provides no info about what it's even supposed to do

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#30]
I just stumbled upon the "check broken gradebook grades" by chance. Could you link me to a description of the problem? I'm not sure what exactly was broken before...

I have a lot of supposedly broken records in this list, when I select all courses and click on Go, it tells me that it fixes all of them:

Fetching affected records... OK (needed 190.35911560059 ms)
1224 records affected.
Building digests... OK (needed 18.074989318848 ms)
Correcting gradebook grades... OK (needed 1540.9979820251 ms)
Informing graders... OK (needed 85.877895355225 ms)

Yet when I click on "check broken gradebook grades" again, I still see the same list, and no grades in the gradebook of affected courses seem to have changed.

It would be helpful to provide more information to your users when you provide a function like that (eg link to the problem description this is supposed to fix, etc.)

**Comment by phager-at** [comment]
Hi,

thanks for stumbling upon this very old script (it only affected v2.9.0 installations, and the error was fixed back then via this script in v2.9.1). I removed it (as well as another legacy upgrade script) from the current master branch, and it should be gone from v3.6.0 on, which will be released hopefully in January 2019.

(I'll leave this issue open for now, and will close it, as soon as the fixed version is published!)

cheers and merry christmas,
Philipp

**Comment by goggo24** [comment]
included in v.3.6.0 - coming soon!
