### ISSUE TITLE
Filter the Export view by a moodle group

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#33]
We have got a Moodle course that corresponds to several exercise groups, all doing the same exercises in separate seminar rooms. These groups are represented as Moodle participant groups. Is it possible to filter the Export view by such Moodle groups?

**Comment by goggo24** [comment]
You can filter the Export view by using the group mode in the checkmark instance. If you set the group mode to "seperate groups" or "visible groups", in the export tab in the area _data setting_ a dropdown appears, where you can restrict the view to a special group. 
Additionally you can also use the _export setting_ "Groups as separate PDFs" - than the output will be created per moodle group from the course. 
<img width="335" alt="group" src="https://user-images.githubusercontent.com/16721900/54070818-5c595800-4265-11e9-83d9-e226ec62fa6d.png">

**Comment by jondo** [comment]
Great, thank you!
