### ISSUE TITLE
improvement suggestion: change order of dropdown for bulk processing

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#34]
I just got a tiny improvement suggestion by one of our teachers, which is very easy to implement:

She said that 95% of the time, if she uses bulk processing on the submissions page, she wants to grade automatically, not grant an extension to the selected students - so it would be great if this was the default value for the dropdown field.

This can easily be done by changing the order of the two if-statements in line 2161 and 2166 in locallib.php, so the result looks like this:

   ```
        
 if (($this->checkmark->grade <= 0)) {
                // No autograde possible if no numeric grades are selected!
                $mform->addElement('html',
                                   $OUTPUT->notification(get_string('autograde_non_numeric_grades', 'checkmark'), 'error'));
                $grp[0]->addOption(get_string('grade_automatically', 'checkmark'), 'grade', array('disabled' => 'disabled'));
            } else {
                $grp[0]->addOption(get_string('grade_automatically', 'checkmark'), 'grade');
                $enablebulk = true;
            }

            if (has_capability('mod/checkmark:manageoverrides', $this->context)) {
                $grp[0]->addOption(get_string('grant_extension', 'checkmark'), 'extend');
                $grp[0]->addOption('---', '', ['disabled' => 'disabled']);
                $enablebulk = true;
            }

```

**Comment by goggo24** [comment]
Thanks for reporting! I will include it in our backlog and discuss it with our team.

**Comment by jondo** [comment]
@goggo24 What was your discussion result?

**Comment by goggo24** [comment]
The order will be changed in v.3.10 - thanks for your suggestion. v.3.10 coming soon!
