### ISSUE TITLE
checkmark sends system notifications to users not enrolled in the course

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#35]
using checkmark v3.6-dev 2018081701 on Moodle 3.6.2+ (Build: 20190201)

if the option "Email alerts to teachers" is activated, checkmark utility will write a system notification to all users with the right to grade checkmarks in the course, even users that are not actually enrolled in the course, but only have a role assignment on the **category** that contains the course.

this is inconsistent with how other Moodle activities behave, and annoying to users that administrate big course categories without actually being enrolled in the course.

reproduce:

1. create a course category and assign a user the role "teacher" or any role with the right to grade checkmark activities for that category
2. create a course in that category
3. create a checkmark mod in that course. activate "Email alerts to teachers" 
4. enrol a student and submit something in the checkmark
-> user that has "administrator" role on the category will get a system notification without actually being enrolled in the course

**Comment by goggo24** [comment]
Thanks for reporting! We will have a look at this as soon as possible. If you can provide a pull request, we would be happy to accept it.

**Comment by goggo24** [comment]
already fixed in v.3.7.1
