### ISSUE TITLE
improvement: change link to submissions to resemble that of moodle assignments

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#36]
small ui improvement suggestion:

- in moodle assignments, viewing the submissions is a button
- in checkmark, it is a link, which is much less noticeable and often overlooked by teachers

therefore, I would suggest adding the btn-class to the link, which can be done with two tiny changes to **locallib.php**:

in line 511, add **text-center** as a class:

>  echo html_writer::tag('div', $this->submittedlink(), array('class' => 'text-info text-center '));

starting from line 845, add the **btn btn-secondary** class to the link:

>if ($cnt = $this->count_real_submissions($group)) {
>    $submitted = html_writer::tag('a', get_string('viewsubmissions', 'checkmark', $cnt),
>     array('class' => 'btn btn-secondary', 'href'  => $urlbase.'submissions.php?id='.$this->cm->id,
>            'id' => 'submissions'));
> } else {
>      $submitted = html_writer::tag('a', get_string('noattempts', 'checkmark'),
>        array('class' => 'btn btn-secondary', 'href'  => $urlbase.'submissions.php?id='.$this->cm->id,
>             'id' => 'submissions'));
>       }

**Comment by goggo24** [comment]
Thanks for reporting and providing a code for the change! We will discuss it and let you know, if it fits in our roadmap.

**Comment by goggo24** [comment]
Included in v.3.11 - coming next week.
