### ISSUE TITLE
Resolve conflicting Moodle 3.7 compatibility info

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#40]
The (default-displayed) [README.md from the master branch](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/master/README.md) currently says "This version is for Moodle 3.6.", while the [plugin webpage](https://moodle.org/plugins/pluginversion.php?id=20125) and the [README.md of the MOODLE_37_STABLE branch](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/MOODLE_37_STABLE/README.md) say "This version is for Moodle 3.7.".

Please merge the MOODLE_37_STABLE into the master to get the README updated.

**Comment by goggo24** [comment]
Thanks for reporting. We missed to push the newest code to the master - now its up to date ;)
