### ISSUE TITLE
Please release version 3.8.0 before end of January 2020

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#41]
Our IT department wants to switch to Moodle 3.8 in February 2020, and will drop this plugin if there is no current release, which would force many exercise groups back to pen-and-paper.

(Note to self: This date was internally given in [IMSD-6302](https://jira.jku.at/servicedesk/customer/portal/1/IMSD-6302).)

**Comment by goggo24** [comment]
We cannot promise anything, but of course we will try to release the version as soon as possible. Our AMC Partner will update end of february 2020 by themselves, so until this date the version will be probably published and available.

**Comment by jondo** [comment]
I am currently trying to find out until when exactly our IT department needs plugin version 3.8. In https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/issues/45#issuecomment-576449296 you just said that 3.8 is "coming soon". That's great! I hope it's soon enough for me.

**Comment by goggo24** [comment]
We are just doing the last tests and hopefully no bugs appear. Checkmark will be published at the latest middle of februar.

**Comment by jondo** [comment]
My IT department says that our Moodle update will happen on February 18, and that the old Checkmark version will only be uninstalled if it is incompatible with the new Moodle version. Is it?

**Comment by jondo** [comment]
Sorry, I only noticed your answer now. Middle of February works fine, thank you!
