### ISSUE TITLE
Provide a field "Additional files" like assignments

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#42]
Assignments have got a field "Additional files" that can be used to provide e.g. a PDF file that contains the assignment. Similarly, I suggest a field to provide a PDF file containing the examples that have to be solved (as rendered LaTeX with embedded pictures).

Workaround: Manually upload the PDF file to Moodle, then link to it in the Description field.
(In the "Create link" dialog, access the file picker via "Browse repositories...", then "Upload a file" there.)

**Comment by goggo24** [comment]
Thanks for the suggestion - that's true, it would help a lot :) If you can provide a pull request, we are happy to merge it back. If not, I will discuss it within the AMC and come back later & let you know, what we decide. For me personally, this issue is more important/interesting than your #50.

**Comment by jondo** [comment]
Sorry, I am not able to create a pull request.
As for the comparison, I'd prefer #50 if I could choose, because #50 does not have any workaround.

**Comment by goggo24** [comment]
Feature will be included in v.3.9.0. - coming soon!
