### ISSUE TITLE
Optionally skip the example preview

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#45]
Currently, when students open a checkmark activity, they see the example preview and need to find and click "Add submission" to proceed. I would like to configure the activity such that this preview is skipped.

(Edit after first practical experience: I told my students about the "Add submission" button, but still one person got stuck at the preview.)

**Comment by goggo24** [comment]
We are also not 100% happy with the workflow and started last week a discussion about it. The reason for the button/preview is that a student doesn't change accidentally his/her submission. We are just thinking to set the button additionaly on the top as well. Do you think this would help in your case too?

**Comment by jondo** [comment]
Thank you for the update! Nice to hear that this is discussed!

I do not see why this protection against accidental changes is necessary. People have to additionally and consciously press "Save changes" anyway.

Having A second "Add submission" button higher up in the page (directly after "No checkmarks have been submitted") might improve user guidance a tiny little, but having two buttons for the same action is bad UI.

**Comment by goggo24** [comment]
In 3.7 as a quick fix the 2nd button was implemented. Now in 3.8 as a student you immediately come to the edit mode, there's no preview anymore - coming soon!
