### ISSUE TITLE
display past checkmarks in calendar / timeline

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#46]
If the due date is set, checkmark activities will be shown in the calendar and timeline on the Moodle Dashboard.

However, they disappear once the due date is in the past.

This is inconsistent with the behaviour of other Moodle activities (Assignment, Quiz, etc etc.), which stay in calendar after their due date passes and thus should be changed.

This is especially relevant in cases where the due date is already in the past, but the cutoff date is not yet reached - students will not see the checkmark date in their calendars any more, even though they could still make a submission there.

**Comment by goggo24** [comment]
Thanks for your feedback, We will have a look on the current behavior within the functionally test for v.3.8.0. and let you know, what we decide. If you already fixed it on your side locally, we would be happy about a pull request and are willing to merge it back.

**Comment by goggo24** [comment]
Included in v.3.11.2 - have fun!
