### ISSUE TITLE
checkmark does not allow students to submit when group mode is enabled but there are no groups in the course

### ISSUE THREAD

**Issue by stemiwe** [academic-moodle-cooperation/moodle-mod_checkmark#47]
reproduce:
1) create a checkmark activity
2) check as students that you see the submit button
3) enable group mode (visible or separate groups) as a teacher
4) check as students - the submit button is no longer there

no other activity behaves like that, submissions should not be blocked just because the course has no groups. 

this is a small issue because of course normally you do not have group mode on activities enabled in a course without groups, but this happened in a course that was copied over from last semester and confused us a lot, since to my knowledge no other activity in moodle behaves this way

**Comment by goggo24** [comment]
Thanks for reporting. We also noticed it ;) It will be fixed and the fix will be included in v.3.7.1. - coming soon!

**Comment by goggo24** [comment]
3.7.1 already published ;)
