### ISSUE TITLE
"Grade automatically" for lots of participants

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#48]
I have got more than 280 students in a Moodle course.

In the Submissions view of a checkmark activity, is there any way to apply the "grade automatically" to all of them at once? Currently I have to set the "Submissions shown per page" to 100, then process each page separately.

**Comment by goggo24** [comment]
You can set the "Submissions shown per page" setting to ALL, than all submissions should be shown on a page. Did it work? Cheers, Eva

![all](https://user-images.githubusercontent.com/16721900/68527772-0c96c900-02eb-11ea-98e0-e8e5a50653fa.png)

**Comment by jondo** [comment]
Yes, this works, thank you!
I just did not notice the "All" option because of #52.
