### ISSUE TITLE
Submissions: "Show: Not submitted" is missing ("Show: Require grading" does not show students without submission)

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#49]
Context: I have got more than 280 students, so I need to use bulk processing.

Currently (v3.7.0) in the Submissions view, when I select "Show: Require grading", people that did not submit anything are not shown. However, in my case they do require a grading (of zero points), so I would expect them to be shown.

My workaround is to select "Show: All", then to press the "Select: Ungraded" button. This fortunately also selects the people without submission.

Could it be that currently empty submissions and missing submissions are treated differently here?
I don't think that they should.

**Comment by goggo24** [comment]
I will have a look as soon as possible and come back with further information.

**Comment by goggo24** [comment]
You are right, these assignments are not shown, but it's the same behaviour as with assignment.  Ungraded only filters students, which have uploaded an assignment. In the assignment it's possible to filter after "not submitted" and that's missing in checkmark. 
I think it would be help, if you could filter for that - i will put it in our backog.

**Comment by jondo** [comment]
The 3.9.0 [changelog](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/master/CHANGELOG.txt) mentions this issue:
```
* [FEATURE] #6531 Add filter in Submissions/Export to only display users who haven't made
                  a submission [github #49]
```

**Comment by goggo24** [comment]
yes - have fun ;)
