### ISSUE TITLE
Missing SVG version of the activity icon

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_checkmark#5]
There is only the legacy `pix/icon.gif` available. It does not look too nice among all the other newly designed SVG icons:

![screenshot_2015-09-03_18-18-59](https://cloud.githubusercontent.com/assets/85831/9664215/b5c7307e-5268-11e5-9575-7c2af148261b.png)

See https://docs.moodle.org/dev/Moodle_icons for relevant guidelines.

**Comment by kaspot** [comment]
I'm really sorry that there are such obvious things missing - we will definitely try to fix these thins asap - will contact the developer asap.

**Comment by mudrd8mz** [comment]
Not an issue any more - a mistakenly uploaded old version has been reviewed.
