### ISSUE TITLE
Please list "All" after "100" in the "Submissions shown per page" selection

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#52]
In the Submissions view of a checkmark activity, the "Submissions shown per page" should have the entry "All" after the largest number, not before the smallest, see
![submissions-shown-per-page](https://user-images.githubusercontent.com/21648/68540615-491eff00-0395-11ea-8265-c28e239d7cc6.png)

I tripped over this and did not notice the "All" entry, causing #48.

**Comment by goggo24** [comment]
Thanks for reporting and providing a pull request. At the moment we are copying the behavior from moodle core activity assignment. I will discuss it within the AMC and I'll return you our decision. Eva

**Comment by jondo** [comment]
I have filed the [corresponding upstream issue](https://tracker.moodle.org/browse/MDL-67436). Please vote, if you support it :-)

**Comment by goggo24** [comment]
I think ALL is the first entry because it's the default value. Nevertheless - if something changes in Moodle core, we will be happy to include it in our plugin as well but for now, we won't fix it.

**Comment by jondo** [comment]
I understand.

**Comment by jondo** [comment]
I have now [fixed this upstream for Moodle 3.10](https://tracker.moodle.org/browse/MDL-67436), therefore reopening this issue. I will update the [corresponding pull request](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/pull/53) soon.

**Comment by jondo** [comment]
The pull request is now updated. Please merge.

**Comment by jondo** [comment]
And please remove the "wontfix" tag, which has become obsolete.

**Comment by jondo** [comment]
@goggo24, can you please remove the obsolete "wontfix" tag?

**Comment by jondo** [comment]
@geichelberger , can you please take a look at my pull request before it becomes stale again?

**Comment by goggo24** [comment]
@jondo now that also moodle core (e.b. assignment) provides all after the biggest number, we will also include it in our plugin.

**Comment by goggo24** [comment]
Included in v.3.11.0 - coming next week.
