### ISSUE TITLE
Bug: Call to undefined method stdClass::get_examples()

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_checkmark#54]
Hi guys,

we recently started using this plugin in our Moodle instance and we encountered this error message:

`Fehler: Call to undefined method stdClass::get_examples()
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 1560 of /mod/checkmark/lib.php: Error thrown
line 1529 of /mod/checkmark/lib.php: call to checkmark_getsubmissionstats()
line 1875 of /mod/checkmark/lib.php: call to checkmark_getsummarystring()
line 211 of /blocks/course_overview_campus/locallib.php: call to checkmark_print_overview()
line 244 of /blocks/course_overview_campus/block_course_overview_campus.php: call to block_course_overview_campus_get_overviews()
line 321 of /blocks/moodleblock.class.php: call to block_course_overview_campus->get_content()
line 230 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1233 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 643 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of /var/local/lib/moodle/localcache/moodle_test/mustache/1571921698/boost_campus_child/__Mustache_e8d8ae873a984614cbb0bd0c2a191036.php: call to Mustache_Context->findDot()
line 13 of /var/local/lib/moodle/localcache/moodle_test/mustache/1571921698/boost_campus_child/__Mustache_7cc05a77adbd15adc1f180a5e50537ed.php: call to __Mustache_e8d8ae873a984614cbb0bd0c2a191036->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_7cc05a77adbd15adc1f180a5e50537ed->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 146 of /theme/boost_campus/layout/columns2.php: call to renderer_base->render_from_template()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of /my/index.php: call to core_renderer->header()`

It will show up when a student added his voting to the activity and then goes back to the Dashboard. There we have placed the plugin block_course_overview_campus which calls the function checkmark_print_overview() that causes the error. As the course news are deprecated since the Dashboard overhaul in Moodle 3.3 and will be removed with Moodle 3.8 you could simply remove this function entirely. Or, of course, you can fix the error within the function and keep it in the plugin.

Best, Kathrin

**Comment by goggo24** [comment]
Thanks for reporting. When the function is no longer in use, a removal is probably the simplest solution - we will have a look! See you, Eva

**Comment by goggo24** [comment]
Function will be removed in v3.8.0 - coming soon!
