### ISSUE TITLE
Submissions: Setting 'no grade' to zero points is often not saved

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#55]
On the Submissions page of our checkmark assignments, when I grade ungraded persons with zero points, then press `Save all my feedback`, the grades often are not saved. This can e.g. be seen by switching to the Export page.
A second teacher of my course has confirmed this problem.

I am not 100 % sure this happens only when I set the grade to _zero_ - I will observe this further.

Often, entering the grade works at a second try. In one case I failed five times to set the grade to zero, then set it to 1 point, which worked. After that, changing to zero points also worked. I will now try to use this as workaround and report back if this does not remedy the problem.

A reason might be that there are a lot of students (285) subscribed is this course. However, the problem also appears when the table is filtered (by name) to only a few persons.

I am using v3.7.0.

**Comment by goggo24** [comment]
Thanks for reporting. We haven't noticed the behavior yet. It would be great, if you can provide as with additional information.

**Comment by goggo24** [comment]
We could reproduce the bug and will try to fix it asap.

**Comment by jondo** [comment]
Great! My uninformed guess is that PHP has mixed up 'undefined' with zero.

**Comment by sutter-tw** [comment]
We have observed the same problem on v.3.6.0

**Comment by goggo24** [comment]
Sorry, I forgot to mention that the fix is already included in v.3.7.2 and v3.8.1.

**Comment by jondo** [comment]
FWIW, the fix was https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/commit/08f1ad20a0114775e8b2273a27ca09cc5a468b21.
