### ISSUE TITLE
Submissions page should show per-example statistics

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#56]
It would be good to get an overview of the absolute number of checkmarks (and even more the percentage of the submissions) on each example.

This should be based on the "Visible groups" setting.

**Comment by goggo24** [comment]
You can export the assignment from the activity over the "export" tab. There it's possible to make seperate PDFs for each group. So you get a quick overview of the checkmarks of all students.

Do you know our extension? The **checkmark report (local/checkmarkreport)** is an extension to the module checkmark and shows the marks and grades for one or more checkmarks in a tabular form. The overview displays the amount of marks, the grades and the percentual allocation. Also you can export the information. Can you have a look, if you find the information you need!

Does that help?

**Comment by jondo** [comment]
This percentage overview of "checkmark report" seems to be exactly  what I want. I will ask our IT department to install it.

**Comment by jondo** [comment]
On second thought, it's not worth bugging the IT to install another extension just for displaying those percentages. I'll continue exporting the grades to ODS and computing the percentages there.
