### ISSUE TITLE
Export should optionally provide sequential numbering

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#57]
Sometimes I need to select a participant randomly. For this, it would be useful if the exported PDFs had a sequential numbering of the table lines.

**Comment by jondo** [comment]
Might this be low effort?

**Comment by goggo24** [comment]
I have already put the issue in our backlog for our next version - please be patient.

**Comment by goggo24** [comment]
included in v.4.0.0 and 3.11.6
