### ISSUE TITLE
Submissions: "Select Ungraded" should not be influenced by comment

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#58]
I am using version 3.8.0 of the plugin, with Moodle 3.8.

On the submissions page, when I disallow quick grading and choose Select Ungraded, the lines without grades, but with a comment are not selected.

For automatic grading I need all ungraded lines to be selected, whether they already have a comment or not.

**Comment by goggo24** [comment]
Thanks for reporting - we will see, what we can do.

**Comment by goggo24** [comment]
Yes, you are right - we fixed it in v.3.10 - also assignments with comment are now selected when you call ungraded. 
v.3.10. coming soon ;)
