### ISSUE TITLE
 Submissions dataloss risk: With quick grading, "Select" should not change the example checkmarks

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#59]
I am using version 3.8.0 of the plugin, with Moodle 3.8.

On the submissions page, when I activate quick grading and choose any of the "Bulk processing->Select" options, not only the line selection checkboxes are changed, but also the examples' checkmark checkboxes!

My workaround: deactivating quick grading.

**Comment by jondo** [comment]
Fortunately, "grade automatically" does not use the wrongly displayed example checkmarks, but only the saved ones.

**Comment by goggo24** [comment]
Error shouldn't appear anymore - already fixed with v.3.8.1
