### ISSUE TITLE
Error after Upgrade moodle-mod_checkmark to the latest Version

### ISSUE THREAD

**Issue by Rainsperger** [academic-moodle-cooperation/moodle-mod_checkmark#64]
After Upgrading mod_checkmark to version moodle311_2021052800 I cannot open open courses, which uses this plugin!

Error message: Error: Object of class stdClass could not be converted to a string

Is there a solution or a workaround here?

I use moodle 3.11.

Thanks!

**Comment by goggo24** [comment]
We will have a look.

**Comment by bin-der-daniel** [comment]
@Rainsperger I am sorry to hear that.

The error you stated has never happened in our development or testing process. Therefore, I would require further information. Can you send me a screenshot of the error and the attached stack trace and/or an export of the course in question? 
Thank you for your help!

**Comment by Rainsperger** [comment]
[Error.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/files/6622646/Error.pdf)

If I rename the folder in moodle from checkmark to checkmark.bak, I have access to the course!

**Comment by bin-der-daniel** [comment]
Thanks. Would you mind sending me another screen shot of the error but this time using the "Developer" logging level. You can change that setting here: 
![image](https://user-images.githubusercontent.com/45862504/121331373-19d8c700-c917-11eb-946e-8f357f3c541e.png)

**Comment by Rainsperger** [comment]
Fehler
Fehler: Object of class stdClass could not be converted to string
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 1389 of /mod/checkmark/lib.php: Error thrown
line 7918 of /lib/moodlelib.php: call to checkmark_print_recent_activity()
line 213 of /blocks/recent_activity/block_recent_activity.php: call to component_callback()
line 74 of /blocks/recent_activity/block_recent_activity.php: call to block_recent_activity->get_modules_recent_activity()
line 341 of /blocks/moodleblock.class.php: call to block_recent_activity->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 27 of /theme/lambda/layout/columns3.php: call to block_manager->region_has_content()
line 1396 of /lib/outputrenderers.php: call to include()
line 1326 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 245 of /course/view.php: call to core_renderer->header()

**Comment by bin-der-daniel** [comment]
That bug is occurring when using Checkmark alongside with a "Recent activities" block. A fix is on the way. Thanks again for reporting :slightly_smiling_face:

**Comment by Rainsperger** [comment]
My workaround to fix this error temporarily: I replaced the file lib.php with the file lib.php from the backup of the older version!

**Comment by goggo24** [comment]
v.3.11.1 is published.
