### ISSUE TITLE
 Issues highlighted by admin/cli/check_database_schema.php

### ISSUE THREAD

**Issue by abias** [academic-moodle-cooperation/moodle-mod_checkmark#66]
Every now and then, we are running the admin/cli/check_database_schema.php script in our Moodle installation.

This time, these issues were highlighted:

```
-------------------------------------------------------------------------------
checkmark_submissions
 * column 'timemodified' should allow NULL (I)
-------------------------------------------------------------------------------
checkmark_overrides
 * Unexpected index 'mdl_checover_tim_ix'.
-------------------------------------------------------------------------------
```

As https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/master/db/upgrade.php is quite long and complicated and as we are using the plugin for some time now, I did not find an immediate discrepancy between https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/master/db/install.xml and https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/blob/master/db/upgrade.php which might have caused this issue.

May I ask you for your kind feedback about these reported issues? Should I just fix them locally in our database or is this something which could also affect other Moodle instances and should be fixed with an additional step in upgrade.php?

Thanks in advance,
Alex

**Comment by bin-der-daniel** [comment]
Dear Alex!

Sorry for taking some time to answer. I tried running the admin/cli/check_database_schema.php script on my local instance and I wasn't getting any error in regards to checkmark. Additionally, I was going through the install.xml and upgrade.php files and I wasn't finding any inconsistencies that would led to the error mentioned above. At least that's the case for the current versions of those files.
Therefore fixing the problem locally is fine for the moment. However, please tell me if you find any additional clues.

Yours,
Daniel

**Comment by abias** [comment]
Hi @bin-der-daniel ,

thank you for your investigation and for looking through the plugin history.
I have fixed those two things now locally and would be fine with closing this issue as done.

Cheers,
Alex

**Comment by bin-der-daniel** [comment]
Hey Alex! Thanks for responding and having a look into the code. Would you mind to share your changes with me so I can check if I have missed something?

Cheers,
Daniel

**Comment by abias** [comment]
Hey @bin-der-daniel ,

in the checkmark_submissions table, I changed the column 'timemodified' to allow NULL values.
And in the checkmark_overrides table, I dropped the index 'mdl_checover_tim_ix'.

I did this in pgadmin's visual interface, but it should be easy for you to write the corresponding SQL queries if needed.

Cheers,
Alex
