### ISSUE TITLE
Checkmark display problems + grayed out field

### ISSUE THREAD

**Issue by taraghi** [academic-moodle-cooperation/moodle-mod_checkmark#73]
There are a few display problems with the Checkmark (since the last update from 3.11.5 to 3.11.6):

1. 
When you create a checkmark, you get to a normal view where you can enter the number of examples under "Checkmark". 
If you save and edit the checkmark again, the individual function is set and you have to deactivate it to get to the number of examples like in the normal view.

2.
In some checkmarks, the number of examples is also grayed out and you can no longer change it, even though no students have submitted their work here yet. 
What is the reason for this and how can I change the number of examples?

3. 
The checkmark opens in the future.
On the course page the date is not displayed with "Opened" as with other activities, but with [[activity:opens]].
Also this does not happen in all Kreuzerl exercises, but in some courses 

![Bildschirmfoto 2022-11-08 um 11 20 32](https://user-images.githubusercontent.com/204101/202223828-8cccea62-3266-406e-9268-1c2215170da1.png)
![Bildschirmfoto 2022-11-08 um 11 22 11](https://user-images.githubusercontent.com/204101/202223834-6431f0e0-cb8b-4eea-9ee0-8f36cc18a6b5.png)
![Bildschirmfoto 2022-11-08 um 11 23 27](https://user-images.githubusercontent.com/204101/202223837-6c184bd0-0b3c-4153-af85-82a65bae00f7.png)
![Bildschirmfoto 2022-11-08 um 11 25 07](https://user-images.githubusercontent.com/204101/202223839-979b3717-93bd-4945-b99b-43a5ad6a85ee.png)

**Comment by goggo24** [comment]
Thanks for reporting. We will have look at it.

**Comment by mwreichel** [comment]
@taraghi:
We already had a detailed look on the mentioned behaviour and the work on bugs no. 1 and 3 of your list will start soon.

Please could you send us further information concerning no. 2. We weren't able to watch this bug with our instances (neither with checkmark 3.11.6, nor with checkmark 4.0).
Does this bug still occure and if so, could you give us any assume for its reason (e.g. any specific settings or did it happened with older checkmarks, which already existed before the latest upgrade, ...)?

Thanks.

**Comment by taraghi** [comment]
@MWRAMC 
Sry for the late answer.

I was not able to reproduce case 2 neither on the test server nor in a sample course on productive server. It only occurs with a checkmark exercise that the instructor has in his course. I think it is really because he reused the activity from the last year (courses are reused in our Moodle each semester). The students are now all unenrolled, but it is still recognized that checkmarks have already been submitted here.

**Comment by mwreichel** [comment]
@taraghi,
thank you for your answer.
In the meantime we did some further tests concerning this behaviour too, but still weren't able to watch it. Because of your comment, it might be any increment and won't be fixed yet.
The other bugs shouldn't appear with the next version which will be published soon.

**Comment by mkemmerling** [comment]
Fixed with version 3.11.7.
