### ISSUE TITLE
Display problems of selection fields together with FontAwesome 6

### ISSUE THREAD

**Issue by AntonT76** [academic-moodle-cooperation/moodle-mod_checkmark#76]
Hi,

I'm not shure if it is a problem of FontAwesome 6, Boost Union or Checkmark Plugin, but I will describe the issue here:

We have detected a display problem in the activity checkmark if we are using FontAwesome6: If a teacher configures a checkmark and changes to "submissions", normally the teacher can see the entries of the students in the selection fields. But the selection fields only show full black and read selection fields (red fields are overwritten items by teacher), but no entries of the students ( = crosses).

It seems to be that it depends on FontAwesome 6, because with FontAwesome 4 it works. In Boost Union Theme there is a possibility to enable and upload FontAweSome 6-files, so Version 6 will be used in the whole platform. Please see screenshots below: one with FontAwesome 4 and other with FontAwesome 6.

We are using checkmark plugin (v4.1.0, 2022120700) together with Moodle 4.1.4. and Boost Union Theme (v4.1-r8, 2023010515).
![checkmark_fa4](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/assets/66412602/50f87c70-a527-4fc4-9376-2443271dcc6a)
![checkmark_fa6](https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/assets/66412602/66804e9b-5941-40ea-a852-8ee7afff400f)

br, Anton

**Comment by goggo24** [comment]
You changed the version of fontawesome here => _theme_boost_union | fontawesomeversion_ - right?

**Comment by AntonT76** [comment]
Hi @goggo24, yes, we changed it in Boost Union (theme_boost_union - fontawesomeversion) to "Update to FontAwesome 6 Free" and did an upload of css and webfonts-files in (theme_boost_union - fontawesomefiles).

br, Anton

**Comment by mwreichel** [comment]
Hi @AntonT76,
quite late, but good news for you: a bugfix for this is now available in our latest version of 4.1, which was published today.

All the best,
Martin

**Comment by AntonT76** [comment]
Hi @mwreichel , thank you, I will update the plugin asap.
br, Anton
