### ISSUE TITLE
Description should be visible for students and guests

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_checkmark#78]
I have given some people guest access to my course, and they have got the right to see assignment and checkmark activities. They can see and download the "additional files" in those activities.

 They can also see the description within the assignment activities, however they do not see the description of checkmark activities. They should also see those.

Workaround would be to use "Display description on course page", but I do not want to clutter my course page with that.

This is on Moodle 4.2.

**Update 2024-04-23: The description is also invisible for the student role!** It also disappears for me when I temporarily "switch role to ..." student. This is a regression, since I used this functionality in former years.

**Comment by mwreichel** [comment]
Hi @jondo ,
thanks for reporting this. We'll have a look on this.

Martin

**Comment by mwreichel** [comment]
We will fix this bug asap.

Martin

**Comment by jondo** [comment]
This also happens with the student role! I updated the issue description.

**Comment by mwreichel** [comment]
Hi @jondo,
we already fixed the bug and it will be part of the next minor-release of the plugin.

Thanks again for reporting.
Martin

**Comment by jondo** [comment]
This was closed by commit https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/commit/5810f672208a59fbf158a4c7449be1df9d6e7966, contained in release 4.3.1.

**Comment by LisaE14** [comment]
Guten Tag,

ich bin bis einschließlich 10. Juni 2024 nicht im Büro.
In dringenden Fällen wenden Sie sich bitte an meine Kolleg*innen unter der DW 1111 oder per E-Mail an ***@***.***

Mit freundlichen Grüßen
Lisa Eckerstorfer

>>> Robert Pollak ***@***.***> 06/06/24 18:45 >>>

This was closed by commit https://github.com/academic-moodle-cooperation/moodle-mod_checkmark/commit/5810f672208a59fbf158a4c7449be1df9d6e7966, contained in release 4.3.1.
