### ISSUE TITLE
Bug message in export when showing/ hiding first column (checkboxes)

### ISSUE THREAD

**Issue by XTRage** [academic-moodle-cooperation/moodle-mod_checkmark#80]
We are running stable 4.1 version and course participants with the teacher role are not able to export the pdfs with the checkmarks.
They are getting the "There are no users to be displayed!" error, despite there of course users being present.
Otherwise the users with manager role are able to export the pdfs without issues.

Capabilities in regards to checkmark are same for both teachers and managers.

**Comment by mwreichel** [comment]
Hi @XTRage 
thank you for your request. We'll have a closer look on that...

All the best,
Martin

**Comment by XTRage** [comment]
HI @mwreichel 
thank you for your message, in the meantime we were able to reproduce the exact problem.
The issue has nothing to do with roles and can be reproduced by both managers and teachers, contrary to our first findings.

As you can see in the attached screencast clicking on +/- (show/hide) of the first column in the list of participants effectively deselects everyone and the error "There are no users to be displayed!" is displayed after clicking the export button.
Showing them again shows that checkboxes are selected, and clicking export again downloads the PDF as expected.

[Screencast from 2024-11-14 09:53:57.webm](https://github.com/user-attachments/assets/3a889b7e-96a0-48ec-afbc-96b32fb82c1f)

We are sorry for not being able to identify the exact issue right away, at first it seemed like roles problem since it popped-up only with some of our teachers, but it ended up being this usability issue that I have described.

**Comment by mwreichel** [comment]
Hi @XTRage,

many thanks for the further details on this bug.
I was able to reproduce it with our system.

We'll fix this bug with an already planned minor release for 4.1.

Martin

**Comment by mwreichel** [comment]
Hi @XTRage,

the bugfix is now available with our latest version of 4.1. We also merged it to 4.4 (as well as to the coming up version for 4.5).

Thank you again for reporting this.

All the best,
Martin
